CREATE SCHEMA `Albuns` /*!40100 DEFAULT CHARACTER SET latin1 */;

CREATE TABLE `Albuns`.`Album` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `banda` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `lancamento` TIMESTAMP NOT NULL,
  `del` TINYINT(1) NOT NULL,
  `capa` MEDIUMTEXT NULL,
  PRIMARY KEY (`idAlbum`)
) ENGINE=InnoDB ;
